### ISSUE TITLE
Question sur la mise en place de vos exports

### ISSUE THREAD

**Issue by estellelandry** [zebobs/Resultats-Campagne-PIX-orga#1]
Bonjour @zebobs,

Je m'appelle Estelle je suis product owner chez pix. 
J'ai vu votre code et je me demandais ce que vous souhaitiez faire avec votre script ? 
Avez vous des besoins qu'on pourrait peut être intégrer au projet Pix ? 
En tout cas c'est trés cool d'avoir créé ça !.

Merci, belle journée.

Estelle.

**Comment by zebobs** [comment]
Bonjour, 

La présentation de pix orga s'améliorent pour les campagnes, mais de nombreux enseignants ne sont pas prêts à utiliser la plateforme pix orga.
J'utilise juste les sorties CSV  pour faire un peu la même chose (en moins jolie) que ce qu'il y a dans les résultats pix orga ! et pouvoir le partager dans un dossier partagé de notre environnement numérique.
Pas de besoin dans pix orga relativement à ceci.

Si il y avait une demande se serait un connecteur pix orga pour les prof à l'aide de leur identifiant académique. Mais cela n'a aucun rapport avec e projet !

Merci

D.

**Comment by estellelandry** [comment]
Un grand merci pour votre réponse. 
En tout cas c'est super que vous ayez pu adapter le fichier pour vos besoins.
Je ferais remonter à mes collègues le besoin de connecteur pix orga. 

Bien à vous,
Estelle.

**Comment by estellelandry** [comment]
Petite question complémentaire, quand vous dites que les professeures ne sont pas prêt à utiliser pix orga, Vous pourriez m'en dire plus ? 
Ce sujet nous intéresse :)

**Comment by zebobs** [comment]
C'est une plateforme de plus à utiliser, un nouveau mot de passe, une nouvelle prise en main. 
Je dis des professeurs et pas tous les !
L'objectif est de toucher un maximum de personnel, montrer que ça fonctionne et que la plateforme pix orga est conviviale.
(Si on rajoute le bouton réenvoyer le mail d'invitation se sera mieux)

**Comment by zebobs** [comment]
J'ai rajouté une information : afficher les élèves n'ayant pas fait le parcours.
A partir du moment ou 1 élève d'une classe a fait le parcours, j'affiche tous les élèves de la classes n'ayant pas fait le parcours.

**Comment by meaz** [comment]
>J'ai rajouté une information : afficher les élèves n'ayant pas fait le parcours.

Ca du coup c'est fort utile!

**Comment by zebobs** [comment]
La sortie comprend désormais un document de synthèse.
