### ISSUE TITLE
Fichier eleves.csv absent

### ISSUE THREAD

**Issue by al1g** [zebobs/Resultats-Campagne-PIX-orga#2]
bonjour,
je viens de tester votre code et je rencontre un pb avec la détection du fichier CSV.
Il est bien présent dans le même dossier que le programme py et pourtant lors de l’exécution sous Thonny,  j'ai le retour :  ! Pas de fichier élèves ...

Une idée du problème ? J'ai bien vérifié le nom du fichier et celui des entête de colonne sans résultat.

Merci

**Comment by zebobs** [comment]
Bonjour, 

Le message d'erreur est en effet un peu trop généraliste.
Cela signifie que la lecture du fichier a été impossible.
Le séparateur est-il bien le ; 
Y a t'il bien les 3 "colonnes" de données

**Comment by al1g** [comment]
Je n'avais pas vu ta réponse avant de poster sur tchap. N'en tiens donc pas 
compte.

Et oui
J'ai bien les 3 colonnes et les points virgule.

Je vais continuer à chercher

Merci

**Comment by al1g** [comment]
Je viens je pense de trouver le pb, il faut a priori que le csv soit enregistré en CSV UTF-8 et pas seulement en CSV
au moins en sortant de Excel
Merci pour le script

**Comment by zebobs** [comment]
En effet, il faut de l'UTF-8.
Cette remarque m'a motivé pour écrire l'automatisation de la récupération des csv.
A tester !
