### ISSUE TITLE
KeyError: "['Nb Convocations'] not in index"

### ISSUE THREAD

**Issue by meaz** [zebobs/Resultats-Campagne-PIX-orga#4]
Depuis la mise à jour d'orga hier, j'ai ce message d'erreur: `KeyError: "['Nb Convocations'] not in index"`

**Comment by zebobs** [comment]
Je vois pas de problème.
As-tu une piste ?

**Comment by meaz** [comment]
Bizarre, cela marche à nouveau. Désolé...
