### ISSUE TITLE
Colonne "certifiable" aléatoire ?

### ISSUE THREAD

**Issue by l-leroux** [zebobs/Resultats-Campagne-PIX-orga#5]
Bonjour,
J'utilise ton script (merci !) et je remarque qqch qui me laisse perplexe : dans le fichier synthèse, certaines classes ont une colonne "certifiable" et d'autres non.... comment est-ce possible ? Parce que aucun des élèves n'a répondu à une campagne de collecte de profil ?
Merci !

**Comment by zebobs** [comment]
Bonjour, 

En effet, l’élément déclencheur de l'affichage d'une colonne est qu'au moins un élève ait fait la campagne.
Pour la colonne certifiable, c'est en effet la campagne de collecte de profils.
Si elle n'apparait pas, c'est qu'aucun élève de la classe n'a répondu.
